### ISSUE TITLE
2.0.0

### ISSUE THREAD

**Issue by jccguimaraes** [jccguimaraes/atom-project-viewer#176]
# Future release

*Key features*

- Rewritten with **Babel** and **Etch**;
- A suite of automation tests for better stability and maintainability.

## discussion / investigation

- [ ] Items in .gitignore are not shown, but should be #167;
- [ ] Open the PV when clicking on status bar item #161;
- [ ] Enable/disable package per project #147.

## adding

- [x] Dock view

## dropping

- [ ] Panel view

## keep / improve

- [ ] Editor view

<br><br><br>

> **please leave in the comments your opinions**

> keep in mind that this is not a feature request beyond what is implemented or in discussion in other issues

> The v2 branch is not yet available as I want it to be a robust and tested package as well as properly documented.

**Comment by jccguimaraes** [comment]
There will be no 2.0.0 of this package
